apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: release-build
  annotations:
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[refs/tags/*]'
spec:
  taskRunTemplate:
    serviceAccountName: tekton-build
    podTemplate:
      hostAliases:
      - ip: 192.168.1.22
        hostnames:
        - git.rossd.net
  timeouts:
    pipeline: 2h0m0s
  workspaces:
  - name: source
    hostPath:
      path: /var/lib/tekton-build/kubegen/source
      type: DirectoryOrCreate
  - name: toolchain
    hostPath:
      path: /var/lib/tekton-build/kubegen/toolchain
      type: DirectoryOrCreate
  params:
  - name: repo
    value: kubegen
  - name: url
    value: https://git.rossd.net/rosco/kubegen.git
  - name: tag
    value: '{{git_tag}}'
  - name: buildPkg
    value: ./cmd/kubegen
  - name: binPrefix
    value: kubegen
  - name: runTest
    value: 'false'
  pipelineRef:
    name: release-build
